# Generated by Django 4.1.5 on 2023-01-03 16:13

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20, verbose_name=' اسم کلاس')),
                ('code', models.CharField(max_length=10, verbose_name='کد کلاس ')),
                ('createdRecord', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'کلاس ',
                'verbose_name_plural': 'کلاسها ',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30, verbose_name=' نام')),
                ('lname', models.CharField(max_length=50, verbose_name='نام خانوادگی ')),
                ('fullname', models.CharField(blank=True, max_length=70)),
                ('gender', models.BooleanField(choices=[(True, 'مرد'), (False, 'زن')], default=True, verbose_name='جنسیت')),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('edu', models.CharField(blank=True, choices=[('Diploma', 'دیپلم'), ('Ac', 'تکنیسین'), ('BSc', 'کارشناسی'), ('MSc', 'کارشناسی ارشد'), ('PHd', 'دکترا')], max_length=10, verbose_name='مدرک تحصیلی')),
                ('dob', django_jalali.db.models.jDateField(verbose_name='تاریخ تولد')),
                ('createdRecord', models.DateTimeField(auto_now_add=True)),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.studentclass')),
            ],
            options={
                'verbose_name': 'دانشجو',
                'verbose_name_plural': 'دانشجوها',
            },
        ),
    ]
